"""is_admin and is_verified fields for users.

Revision ID: 38927832b7c4
Revises: 7ea2f4e18cc4
Create Date: 2019-11-10 14:03:26.331565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38927832b7c4'
down_revision = '7ea2f4e18cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
