"""empty message

Revision ID: 5e2282d6f7ef
Revises: 81549fd19dfa
Create Date: 2020-05-20 15:14:12.085144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2282d6f7ef'
down_revision = '81549fd19dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('phonetic_date', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'phonetic_date')
    # ### end Alembic commands ###
