"""empty message

Revision ID: 81549fd19dfa
Revises: 20d1e1ae46ad
Create Date: 2020-02-26 17:49:03.264884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81549fd19dfa'
down_revision = '20d1e1ae46ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'date')
    # ### end Alembic commands ###
