"""empty message

Revision ID: f84fceb44e3b
Revises: 
Create Date: 2019-10-20 17:09:18.708068

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f84fceb44e3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_signup_datetime', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('phrases')
    op.drop_table('people_quoted')
    op.drop_index('ix_quotes_submitted_datetime', table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('quotes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('submitted_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_person_quoted_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('context', sa.VARCHAR(length=140), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['primary_person_quoted_id'], ['people_quoted.id'], name='quotes_primary_person_quoted_id_fkey'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name='quotes_submitted_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quotes_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_quotes_submitted_datetime', 'quotes', ['submitted_datetime'], unique=False)
    op.create_table('people_quoted',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('people_quoted_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last_name_initial', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='people_quoted_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('phrases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quote_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_quoted_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('phrase_text', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_quoted_id'], ['people_quoted.id'], name='phrases_person_quoted_id_fkey'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='phrases_quote_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='phrases_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('signup_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_signup_datetime', 'users', ['signup_datetime'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
